let resourcesData = [

        {
            id: 0,
            title: 'Miami-Dade Public Library System',
            description: 'Public Library to citizens in the Miami-Dade area',
            category: 'Government',
            url: 'https://mdpls.org/',
        },
        {
            id: 1,
            title: 'Miami-Dade County Public Schools',
            description: 'Public education system serving Miami-Dade County',
            category: 'Education',
            url: 'https://dadeschools.net/',
        },
        {
            id: 2,
            title: 'Jackson Health System',
            description: 'Public healthcare system in Miami-Dade County',
            category: 'Health and Wellness',
            url: 'https://jacksonhealth.org/',
        },
        {
            id: 3,
            title: 'Pérez Art Museum Miami',
            description: 'Contemporary art museum in Miami',
            category: 'Arts and Culture',
            url: 'https://www.pamm.org/',
        },
        {
            id: 4,
            title: 'Greater Miami Chamber of Commerce',
            description: 'Business advocacy organization in Miami-Dade County',
            category: 'Business and Entrepreneurship',
            url: 'https://www.miamichamber.com/',
        },
        {
            id: 5,
            title: 'Miami-Dade Parks, Recreation and Open Spaces',
            description: 'Parks and recreation services in Miami-Dade County',
            category: 'Recreation and Tourism',
            url: 'https://www.miamidade.gov/parks/',
        },
        {
            id: 6,
            title: 'Miami International Airport',
            description: 'Major airport serving the Miami metropolitan area',
            category: 'Travel and Transportation',
            url: 'https://www.miami-airport.com/',
        },
        {
            id: 7,
            title: 'Zoo Miami',
            description: 'Zoo and botanical garden in Miami',
            category: 'Recreation and Tourism',
            url: 'https://www.zoomiami.org/',
        },
        {
            id: 8,
            title: 'Adrienne Arsht Center for the Performing Arts',
            description: 'Performing arts center in Downtown Miami',
            category: 'Arts and Culture',
            url: 'https://www.arshtcenter.org/',
        },
        {
            id: 9,
            title: 'City of Miami Beach',
            description: 'Official website of the City of Miami Beach',
            category: 'Government',
            url: 'https://www.miamibeachfl.gov/',
        },
        {
            id: 10,
            title: 'Frost Science Museum',
            description: 'Science museum and planetarium in Miami',
            category: 'Arts and Culture',
            url: 'https://www.frostscience.org/',
        },
        {
            id: 11,
            title: 'A Practical Business Resource Guide',
            description: 'To open and grow your business in the City of Miami',
            category: 'Business and Entrepreneurship',
            file: 'https://www.miamigov.com/files/assets/public/document-resources/pdf-docs/human-services/miami-business-solutions-guide_508.pdf',
        },
    {
        id: 12,
        title: 'Miami Children’s Museum',
        description: 'Interactive children’s museum in Miami',
        category: 'Arts and Culture',
        url: 'https://www.miamichildrensmuseum.org/',
    },
    {
        id: 13,
        title: 'Miami Seaquarium',
        description: 'Marine park and aquarium in Miami',
        category: 'Recreation and Tourism',
        url: 'https://www.miamiseaquarium.com/',
    },
    {
        id: 14,
        title: 'Florida International University',
        description: 'Public research university in Miami',
        category: 'Education',
        url: 'https://www.fiu.edu/',
    },
    {
        id: 15,
        title: 'PortMiami',
        description: 'Cruise ship and cargo port in Miami',
        category: 'Travel and Transportation',
        url: 'https://www.miamidade.gov/portmiami/',
    },
    {
        id: 16,
        title: 'Bayside Marketplace',
        description: 'Outdoor shopping and entertainment center in Miami',
        category: 'Recreation and Tourism',
        url: 'https://www.baysidemarketplace.com/',
    },
    {
        id: 17,
        title: 'Vizcaya Museum and Gardens',
        description: 'Historic estate and gardens in Miami',
        category: 'Arts and Culture',
        url: 'https://vizcaya.org/',
    },
    {
        id: 18,
        title: 'Miami Design District',
        description: 'Shopping and cultural district in Miami',
        category: 'Arts and Culture',
        url: 'https://www.miamidesigndistrict.net/',
    },
    {
        id: 19,
        title: 'University of Miami',
        description: 'Private research university in Coral Gables',
        category: 'Education',
        url: 'https://welcome.miami.edu/',
    },
    {
        id: 20,
        title: 'Florida Memorial University',
        description: 'Historically black university in Miami Gardens',
        category: 'Education',
        url: 'https://www.fmuniv.edu/',
    },
    {
        id: 21,
        title: 'Biscayne National Park',
        description: 'National park preserving Biscayne Bay and its coral reefs',
        category: 'Recreation and Tourism',
        url: 'https://www.nps.gov/bisc/index.htm',
    },
    {
        id: 22,
        title: 'Jungle Island',
        description: 'Zoological park and botanical garden in Miami',
        category: 'Recreation and Tourism',
        url: 'https://www.jungleisland.com/',
    },
    {
        id: 23,
        title: 'American Airlines Arena',
        description: 'Sports and entertainment arena in Miami',
        category: 'Recreation and Tourism',
        url: 'https://www.aaarena.com/',
    },
    {
        id: 24,
        title: 'Miami Children’s Theater',
        description: 'Youth theater company in Miami',
        category: 'Arts and Culture',
        url: 'https://www.miamichildrenstheater.com/',
    },
    {
        id: 25,
        title: 'Fairchild Tropical Botanic Garden',
        description: 'Botanical garden and conservation center in Coral Gables',
        category: 'Arts and Culture',
        url: 'https://www.fairchildgarden.org/',
    },
    {
        id: 26,
        title: 'Miami Marlins',
        description: 'Major League Baseball team based in Miami',
        category: 'Recreation and Tourism',
        url: 'https://www.mlb.com/marlins',
    },
    {
        id: 27,
        title: 'Miami Heat',
        description: 'National Basketball Association team based in Miami',
        category: 'Recreation and Tourism',
        url: 'https://www.nba.com/heat/',
    },
    {
        id: 28,
        title: 'Bayfront Park',
        description: 'Public park and event space in downtown Miami',
        category: 'Recreation and Tourism',
        url: 'https://www.miamigov.com/Residents/Parks/Bayfront-Park',
    },
    {
        id: 29,
        title: 'Pinecrest Gardens',
        description: 'Botanical garden and cultural arts park in Pinecrest',
        category: 'Arts and Culture',
        url: 'https://www.pinecrestgardens.org/',
    },
    {
        id: 30,
        title: 'Coral Gables Museum',
        description: 'Local history and art museum in Coral Gables',
        category: 'Arts and Culture',
        url: 'https://www.coralgablesmuseum.org/',
    },
    {
        id: 31,
        title: 'Miami-Dade Transit',
        description: 'Public transportation system in Miami-Dade County',
        category: 'Travel and Transportation',
        url: 'https://www.miamidade.gov/transportation/',
    },
    {
        id: 32,
        title: 'Miami Science Barge',
        description: 'Floating marine lab and environmental education center',
        category: 'Education',
        url: 'https://www.miamisciencebarge.org/',
    },
    {
        id: 33,
        title: 'Wynwood Walls',
        description: 'Outdoor street art museum in the Wynwood neighborhood',
        category: 'Arts and Culture',
        url: 'https://www.thewynwoodwalls.com/',
    },
    {
        id: 34,
        title: 'Miami City Ballet',
        description: 'Professional ballet company based in Miami',
        category: 'Arts and Culture',
        url: 'https://www.miamicityballet.org/',
    },
    {
        id: 35,
        title: 'Miami New Drama',
        description: 'Theater company specializing in new works and reimagined classics',
        category: 'Arts and Culture',
        url: 'https://www.miaminewdrama.org/',
    },
    {
        id: 36,
        title: 'Bill Baggs Cape Florida State Park',
        description: 'State park with a historic lighthouse and beautiful beaches',
        category: 'Recreation and Tourism',
        url: 'https://www.floridastateparks.org/parks-and-trails/bill-baggs-cape-florida-state-park',
    },
    {
        id: 37,
        title: 'The Bass',
        description: 'Contemporary art museum in Miami Beach',
        category: 'Arts and Culture',
        url: 'https://thebass.org/',
    },
    {
        id: 38,
        title: 'Wynwood Brewing Company',
        description: 'Craft brewery located in the Wynwood neighborhood',
        category: 'Business and Entrepreneurship',
        url: 'https://wynwoodbrewing.com/',
    },
    {
        id: 39,
        title: 'Miami-Dade County Fair and Exposition',
        description: 'Annual fair showcasing entertainment, food, and agricultural exhibits',
        category: 'Recreation and Tourism',
        url: 'https://www.thefair.me/',
    },
    {
        id: 40,
        title: 'Miami Spice',
        description: 'Citywide dining promotion featuring prix-fixe menus at top restaurants',
        category: 'Recreation and Tourism',
        url: 'https://www.miamiandbeaches.com/offers/temptations/miami-spice-month',
    },
    {
        id: 41,
        title: 'Jewish Museum of Florida - FIU',
        description: 'Museum dedicated to preserving and showcasing Jewish history and culture',
        category: 'Arts and Culture',
        url: 'https://jmof.fiu.edu/',
    },
    {
        id: 42,
        title: 'Perez Art Museum Miami',
        description: 'Contemporary art museum in Miami',
        category: 'Arts and Culture',
        url: 'https://www.pamm.org/',
    },
    {
        id: 43,
        title: 'Deering Estate',
        description: 'Historic site and environmental preserve in Miami',
        category: 'Recreation and Tourism',
        url: 'https://deeringestate.org/',
    },
    {
        id: 44,
        title: 'Wynwood Art Walk',
        description: 'Monthly art and cultural event in the Wynwood neighborhood',
        category: 'Arts and Culture',
        url: 'https://wynwoodmiami.com/art-walk/',
    },
    {
        id: 45,
        title: 'HistoryMiami Museum',
        description: 'Museum dedicated to preserving and celebrating Miami’s history',
        category: 'Arts and Culture',
        url: 'https://www.historymiami.org/',
    },
    {
        id: 46,
        title: 'Miami Children’s Chorus',
        description: 'Youth choir organization in Miami',
        category: 'Arts and Culture',
        url: 'https://www.miamichildrenschorus.org/',
    },
    {
        id: 47,
        title: 'Zoo Miami Foundation',
        description: 'Non-profit organization supporting Zoo Miami',
        category: 'Recreation and Tourism',
        url: 'https://www.zoomiamifoundation.org/',
    },
    {
        id: 48,
        title: 'Marlins Park',
        description: 'Home stadium of the Miami Marlins baseball team',
        category: 'Recreation and Tourism',
        url: 'https://www.mlb.com/marlins/ballpark',
    },
    {
        id: 49,
        title: 'The Wolfsonian',
        description: 'Museum and research center focused on art and design',
        category: 'Arts and Culture',
        url: 'https://www.wolfsonian.org/',
    },
    {
        id: 50,
        title: 'Miami Symphony Orchestra',
        description: 'Professional orchestra performing classical and contemporary music',
        category: 'Arts and Culture',
        url: 'https://www.themiso.org/',
    },
    {
        id: 51,
        title: 'Art Deco Historic District',
        description: 'Neighborhood with preserved Art Deco architecture in Miami Beach',
        category: 'Arts and Culture',
        url: 'https://www.visitsouthbeachonline.com/art-deco-historic-district',
    },



    {
        id: 52,
        title: 'Florida International University',
        description: 'Public research university in Miami',
        category: 'Education',
        url: 'https://www.fiu.edu/',
    },
    {
        id: 53,
        title: 'Miami-Dade County Government',
        description: 'Official website of Miami-Dade County government',
        category: 'Government',
        url: 'https://www.miamidade.gov/',
    },
    {
        id: 54,
        title: 'Miami-Dade Public Schools',
        description: 'Public school district serving Miami-Dade County',
        category: 'Education',
        url: 'https://www.dadeschools.net/',
    },
    {
        id: 55,
        title: 'Small Business Development Center at FIU',
        description: 'Business consulting and resources for entrepreneurs',
        category: 'Business and Entrepreneurship',
        url: 'https://sbdc.fiu.edu/',
    },
    {
        id: 56,
        title: 'Florida Small Business Development Center',
        description: 'Statewide network of business assistance centers',
        category: 'Business and Entrepreneurship',
        url: 'https://floridasbdc.org/',
    },
    {
        id: 57,
        title: 'Miami-Dade County Clerk of Courts',
        description: 'Official website of the Miami-Dade County Clerk of Courts',
        category: 'Government',
        url: 'https://www.miami-dadeclerk.com/',
    },
    {
        id: 58,
        title: 'Miami-Dade County Elections Department',
        description: 'Information on elections and voter registration in Miami-Dade County',
        category: 'Government',
        url: 'https://www.miamidade.gov/global/elections/home.page',
    },
    {
        id: 59,
        title: 'Florida Department of Education',
        description: 'State education agency in Florida',
        category: 'Education',
        url: 'http://www.fldoe.org/',
    },
    {
        id: 60,
        title: 'Miami-Dade College',
        description: 'Public college in Miami-Dade County',
        category: 'Education',
        url: 'https://www.mdc.edu/',
    },
    {
        id: 61,
        title: 'City of Miami',
        description: 'Official website of the City of Miami',
        category: 'Government',
        url: 'https://www.miamigov.com/',
    },
    {
        id: 62,
        title: 'Florida Division of Corporations',
        description: 'Register and manage businesses in Florida',
        category: 'Business and Entrepreneurship',
        url: 'https://dos.myflorida.com/sunbiz/',
    },
    {
        id: 63,
        title: 'Florida Small Business',
        description: 'Resources for starting and growing a small business in Florida',
        category: 'Business and Entrepreneurship',
        url: 'https://www.floridasmallbusiness.com/',
    },
    {
        id: 64,
        title: 'Miami-Dade County Economic Development',
        description: 'Support for businesses and economic development initiatives',
        category: 'Business and Entrepreneurship',
        url: 'https://www.miamidade.gov/economic/',
    },
    {
        id: 65,
        title: 'Florida Department of State',
        description: 'Government agency overseeing elections, cultural affairs, and more',
        category: 'Government',
        url: 'https://dos.myflorida.com/',
    },
    {
        id: 66,
        title: 'Florida Virtual School',
        description: 'Online public school serving K-12 students in Florida',
        category: 'Education',
        url: 'https://www.flvs.net/',
    },
    {
        id: 67,
        title: 'Miami-Dade County Public Library System',
        description: 'Public library system serving Miami-Dade County',
        category: 'Government',
        url: 'https://mdpls.org/',
    },
    {
        id: 68,
        title: 'Florida International University Business Incubator',
        description: 'Support for startup businesses at FIU',
        category: 'Business and Entrepreneurship',
        url: 'https://fiu-startup.fiu.edu/',
    },
    {
        id: 69,
        title: 'Miami-Dade County Office of Economic Development and Trade',
        description: 'Promoting economic development and trade in Miami-Dade County',
        category: 'Government',
        url: 'https://www.miamidade.gov/economicdevelopment/',
    },
    {
        id: 70,
        title: 'Florida Small Business Emergency Bridge Loan Program',
        description: 'Assistance for small businesses impacted by disasters',
        category: 'Business and Entrepreneurship',
        url: 'https://floridadisasterloan.org/',
    },
    {
        id: 71,
        title: 'Florida Department of Economic Opportunity',
        description: 'State agency supporting economic development and job creation',
        category: 'Government',
        url: 'https://floridajobs.org/',
    },
    {
        id: 72,
        title: 'City of Miami Beach Office of Economic Development',
        description: 'Promoting economic growth and development in Miami Beach',
        category: 'Government',
        url: 'https://www.mbrisingabove.com/',
    }

];

export {resourcesData};